config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  root 'users#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :update]
  resources :follows, only: [:create]
  resources :messages, only: [:create, :index]
  get 'messages/masters' => 'messages#masters'
  get 'messages/disciples' => 'messages#disciples'
  put 'follows/update' => 'follows#update'
  get 'mypage' => 'users#mypage'
  get 'admin' => 'users#admin'
  get 'terms' => 'users#terms'
  get 'masters/search' => 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :from_user, class_name: User, foreign_key: :from_user_id
  belongs_to :to_user, class_name: User,   foreign_key: :to_user_id
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :follow, touch: true

  # User.find(1)が師匠、User.find(2)が弟子のとき
  # User.find(1).follows_to.find_by(from_user_id: 2).messages or User.find(2).follows_from.find_by(to_user_id: 1).messagesでメッセージを取得可能
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_many :skills
  has_many :messages

  accepts_nested_attributes_for :skills, allow_destroy: true

  # N:Nの自己結合
  has_many :follows_from, class_name: Follow, foreign_key: :from_user_id, dependent: :destroy
  has_many :follows_to,   class_name: Follow, foreign_key: :to_user_id,   dependent: :destroy
  has_many :master, through: :follows_from, source: :to_user
  has_many :disciple,  through: :follows_to,   source: :from_user

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
      user.name = auth["info"]["name"]
      user.description = auth["info"]["description"]
      user.image = auth["info"]["image"]
      user.email = User.dummy_email(auth)
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def accepted_disciple
    follows_to.map{|follow| follow.from_user if follow.is_accept}.compact
  end

  def no_accepted_disciple
    follows_to.map{|follow| follow.from_user unless follow.is_accept}.compact
  end

  def accepted_master
    follows_from.map{|follow| follow.to_user if follow.is_accept}.compact
  end

  def no_accepted_master
    follows_from.map{|follow| follow.to_user unless follow.is_accept}.compact
  end

  def master_count
    accepted_master.length
  end

  def disciple_count
    accepted_disciple.length
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def skill_list
    skills.pluck(:language)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user?(user)
    current_user == user
  end

  def redirect_login
    unless current_user.present?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  before_action :set_follow

  def update
    @follow.update(is_accept: true)
    render :json => {messages: "承認しました"}
  end

  def create
    if @follow.present? && @follow.is_accept
      render :json => {messages: '承認済みです。', status: 500}
    elsif @follow.present? && !@follow.is_accept
      render :json => {messages: '申請済みです。', status: 500}
    else
      Follow.create!(follow_params)
      render :json => {messages: '弟子入り申請しました。', status: 200}
    end
  end

  private

  def follow_params
    params.require(:follows).permit(:to_user_id, :from_user_id)
  end

  def set_follow
    @follow = Follow.find_by(follow_params)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :redirect_login
  before_action :set_users
  before_action :set_follows
  before_action :set_opponent_user, only: [:masters, :disciples]

  def index
    render 'messages/index.json.jbuilder'
  end

  def create
    if Message.create!(message_params)
      render 'messages/index.json.jbuilder'
    end
  end

  def masters
  end

  def disciples
  end

  private

  def message_params
    params.permit(:follow_id, :content).merge(user_id: current_user.id)
  end

  def set_users
    @users = is_master ? current_user.accepted_disciple : current_user.accepted_master
  end

  def set_follows
    @follows = is_master ? current_user.follows_to : current_user.follows_from
  end

  def is_master
    params[:opponent_user] != 'masters'
  end

  def set_opponent_user
    gon.opponent_user = params[:action]
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

    if @user.persisted?
      sign_in_and_redirect @user
    else
      session["devise.user_attributes"] = @user.attributes
      if @user.save!
        sign_in_and_redirect @user
      end
    end
  end

  def after_sign_in_path_for(resource)
    mypage_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_login, only: [:show, :update, :mypage]
  before_action :set_user, only: [:show, :update]
  before_action :set_is_current_user

  def index
    @top_users = User.joins(:follows_to).group(:id).order('count(to_user_id) DESC').where(is_master: true).limit(3)
    @users = User.all.order('updated_at DESC').where(is_master: true).limit(10)
  end

  def show
    gon.user_id = @user.id
    gon.current_user_id = current_user.id
  end

  def update
    if @user == current_user
      @user.update(user_params)
    end
    render 'users/show.json.jbuilder'
  end

  def search
    @users = User.where(is_master: true)
    @users = @users.where(id: params[:id]) if params[:id].present?
    @users = @users.where('users.name like ?', "%#{params[:name]}%") if params[:name].present?
    @users = @users.where(id: Skill.where(language: params[:skill]).pluck(:user_id)) if params[:skill].present?
  end

  def mypage
    gon.user_id = current_user.id
  end

  def admin
  end

  def terms
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :description, :is_master, :goal, skills_attributes: [:id, :description, :language, :_destroy])
  end

  def set_is_current_user
    @is_current_user = current_user?(@user)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/api_controller_helper.rb
module ApiControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converted_pictures_helper.rb
module ConvertedPicturesHelper
end

app/helpers/picture_controller_helper.rb
module PictureControllerHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="clearFix m_header">
  <div class="innerWrapper">
    <div class="title">
      <a href="/">
        SHISHO
      </a>
    </div>
    <nav>
      <% if user_signed_in? %>
      <div class="pcZone">
        <ul class="menuWrapper pc">
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'gMenu' %></li>
          <li class="gMenu message">
            メッセージ
            <ul class="dropdownMenu">
              <li>
                <%= link_to '師匠', messages_masters_path(), class: 'dropdownContent' %>
              </li>
              <li>
                <%= link_to '弟子', messages_disciples_path(), class: 'dropdownContent' %>
              </li>
            </ul>
          </li>
          <li><%= link_to 'マイページ', mypage_path(), class: 'gMenu' %></li>
          <li><%= link_to '師匠を探す', root_path(), class: 'gMenu' %></li>
        </ul>
      </div>

      <div class="spZone" id="jsMenuWrapper">
        <div class="menuButton" id="js_headerMenuOpen"><i class="fa fa-bars fa-2x"></i></div>
        <ul class="menuWrapper sp">
          <li><%= link_to '師匠を探す', root_path() %></li>
          <li><%= link_to 'マイページ', mypage_path() %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        </ul>
        <div class="overRayer" id="js_headerMenuClose"></div>
      </div>

      <% else %>
        <div class="loginButton"><%= link_to 'ログイン', new_user_session_path, class: 'gMenu' %></div>
      <% end %>
    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHISHO</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:image" content="https://shisho.me<%= asset_path "shisho.png" %>">
    <meta name="twitter:site" content="@pareriva_d_taro">
    <meta property="og:url" content="https://shisho.me">
    <meta property="og:title" content="SHISHO">
    <meta property="og:description" content="【プログラミング独学者向け】あなたの師匠を探しましょう！">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120580952-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-120580952-1');
    </script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= include_gon %>
    <link href="https://fonts.googleapis.com/css?family=Jua" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body class="<%= params[:controller].gsub('/', ' ') %> <%= params[:action] %>">
    <%= render 'layouts/header' %>
    <%= yield %>
    <% if "#{params[:controller]}" != "messages"%>
    <footer class="m_fotter">
      <div class="innerWrapper">
        <div class="title">
          SHISHO
        </div>
        <ul>
          <li>
            <a href="<%= terms_path %>">
              利用規約
            </a>
          </li>
          <li>
            <a href="<%= admin_path %>">
              SHISHOをつくった人
            </a>
          </li>
          <li>
            <a href="https://note.mu/dragontaro/n/n550a38a3261f">
              プログラミングコンサル
            </a>
          </li>
        </ul>
        <div class="copyRight">
          ©️ 2018 宮川 竜太朗
        </div>
      </div>
    </footer>
    <% end %>
  </body>
</html>

app/views/messages/disciples.html.erb
<div id="Message"></div>
<%= javascript_pack_tag 'Message' %>

app/views/messages/masters.html.erb
<div id="Message"></div>
<%= javascript_pack_tag 'Message' %>

app/views/partial/_header_menu.html.erb
<div class="menu">
  <ul>
    <li><a href="/">home</a></li>
    <li><a href="/pictures">gallery</a></li>
    <li><a href="/abouts">about</a></li>
  </ul>
</div>

app/views/users/_users_list.html.erb
<% users.each do |user| %>
  <div class="m_userList">
    <a href="<%= user_path(user.id) %>">
      <h3>
        <img src="<%= user.image %>">
        <%= user.name %>
      </h3>
      <div class="displayMDBox">
        <span class="displayMD">師匠 <%= user.master_count %>人</span>
        <span class="displayMD">弟子 <%= user.disciple_count %>人</span>
      </div>
      <div class="content">
        <%= user.description %>
      </div>
      <div class="skills">
        <% user.skills.each do |skill| %>
          <span class="p_button gray"><%= skill.language %></span>
        <% end %>
      </div>
    </a>
  </div>
<% end %>

app/views/users/admin.html.erb
<div class="innerWrapper content">
  <h1>SHISHOをつくった人</h1>
  <p>
    どうも！SHISHOをつくった宮川 竜太朗と申します！ <br>
    京都大学化学工学を専攻しながらITエンジニアとしてインターンしています。
  </p>
  <h2>SHISHOをつくった目的</h2>
  <p>
    詳しくは、noteにまとめようとは思っているのですが、僕がプログラミングを独学で勉強したときにとても苦労したからです。 <br>
    自分が勉強したときは質問できる人に恵まれました。しかし、全ての人がそのような環境に恵まれているとは到底思えません。 <br>
    エンジニア不足が叫ばれている今の時代に、人に教えているだけの余裕がある人などそういないからです。 <br>
  </p>
  <p>
    確かに、progateなどの登場によりプログラミングの勉強がしやすい環境はどんどん整ってきました。 <br>
    しかし、それでも気軽に質問できる状況はなかなかありません。 <br>
    teratailなどのサービスはありますが、質問に対する敷居が高くあまり質問がされていないように思います。（あくまで僕個人の見解ですが、そう思っているひとも少なくないはず。。） <br>
  </p>
  <p>
    それと同時に勉強した人がアウトプットできる場もあまりないように感じていました。インプットだけでは勉強したとは言えません。
  </p>
  <p>
    そこで、気軽に質問できるサービスを作ることにしました。
  </p>
  <p>
    それがこの、SHISHOというアプリです。少し勉強した人が師匠になることで、気軽にかつ簡単に質問・アウトプットができるプラットフォームを提供します。
  </p>
  <h2>制作に関して</h2>
  <p>
    このアプリは約１週間で大学生が一人でつくったアプリです。 <br>
    頑張ればこれぐらいのアプリならすぐに作れんだと言うことをまず認識していただきたいです。 <br>
    正直めっちゃ辛かったです。１週間でやるとtwitterで宣言してしまったのでやめるわけにはいきませんでした。（200RT超え）
  </p>
  <p>
    使用した技術はruby on railsとjavascriptのreactです。サーバーはAWSのEC2、開発環境はdockerで構築しました。gitによるコード管理もしています。 <br>
    だいたい最近の流行りを使ってます。あと、普段の開発でやっていることと同じです。
  </p>
  <h2>プログラミング界隈を盛り上げたい！</h2>
  <p>
    正直これにつきます。だからやったんです。<br>
    一人の力には限界を感じたので、みんなで盛り上げていきたいな〜と考えております！ <br>
    これと並行してプログラミングコンサルというオンラインサロンもやっています。こちらも随時メンバー募集中です！ <br>
    参加はこちらから↓ <br>
    <a href="https://note.mu/dragontaro/n/n550a38a3261f">プログラミングコンサル</a>
  </p>
</div>

app/views/users/index.html.erb
<div class="innerWrapper">
  <h1>おすすめ師匠</h1>
  <div class="m_topUsers">
    <%= render "users_list", users: @top_users %>
  </div>
  <div class="m_showAndSearchZone">
    <div class="rightContent">
      <h2>検索</h2>
      <div id="SearchForm"></div>
    </div>
    <div class="leftContent">
      <h2>最近の師匠</h2>
      <div class="m_normalUsers">
        <%= render "users_list", users: @users %>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'SearchForm'%>

app/views/users/mypage.html.erb
<div id="editUser"></div>
<%= javascript_pack_tag 'EditUser'%>

app/views/users/search.html.erb
<div id="SearchUser"></div>
<%= javascript_pack_tag 'SearchUser' %>

app/views/users/show.html.erb
<div class="m_showUser innerWrapper">
  <h2>
    <img src="<%= @user.image %>" />
    <%= @user.name %>
    <div class="showDisplayMDWrapper">
      <span class="displayMD">師匠 <%= @user.master_count %>人</span>
      <span class="displayMD">弟子 <%= @user.disciple_count %>人</span>
    </div>
  </h2>

  <ul class="displayTable">
    <li class="clearFix">
      <div class="th">
        自己紹介
      </div>
      <div class="td">
        <%= @user.description %>
      </div>
    </li>

    <li class="clearFix">
      <div class="th">
        目標
      </div>
      <div class="td">
        <%= @user.goal %>
      </div>
    </li>

    <li class="clearFix">
      <div class="th">
        スキル
      </div>
      <div class="td">
        <ul>
          <% @user.skills.each do |skill| %>
            <li class="skillRow">
              <span class="p_button gray"><%= skill.language %></span>
              <%= skill.description %>
            </li>
          <% end %>
        </ul>
      </div>
    </li>
  </ul>
  <% if @user.is_master && @user != current_user %>
    <div id="ApplyButton" class="applyButton"></div>
  <% end %>
</div>
<%= javascript_pack_tag 'ApplyButton'%>

app/views/users/terms.html.erb
<div class="innerWrapper content">
  <h1>利用規約</h1>
  <p>この利用規約（以下，「本規約」といいます。）は，SHISHO（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>
  <h2>第1条（適用）</h2>
  <p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>

  <h2>第2条（利用登録）</h2>
  <ul>
  <li>登録希望者が当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</li>
  <li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
  <ul>
  <li>（1）利用登録の申請に際して虚偽の事項を届け出た場合</li>
  <li>（2）本規約に違反したことがある者からの申請である場合</li>
  <li>（3）その他，当社が利用登録を相当でないと判断した場合</li>
  </ul></li>
  </ul>

  <h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
  <ul>
  <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。</li>
  <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
  </ul>

  <h2>第5条（禁止事項）</h2>
  <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
  <ul class="child">
  <li>（1）法令または公序良俗に違反する行為</li>
  <li>（2）犯罪行為に関連する行為</li>
  <li>（3）当社のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
  <li>（4）当社のサービスの運営を妨害するおそれのある行為</li>
  <li>（5）他のユーザーに関する個人情報等を収集または蓄積する行為</li>
  <li>（6）他のユーザーに成りすます行為</li>
  <li>（7）当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
  <li>（8）その他，当社が不適切と判断する行為</li>
  </ul>

  <h2>第6条（本サービスの提供の停止等）</h2>
  <ul>
  <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
  <ul>
  <li>（1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
  <li>（2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
  <li>（3）コンピュータまたは通信回線等が事故により停止した場合</li>
  <li>（4）その他，当社が本サービスの提供が困難と判断した場合</li>
  </ul>
  </li>
  <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</li>
  </ul>

  <h2>第7条（利用制限および登録抹消）</h2>
  <ul>
  <li>当社は，以下の場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
  <ul>
  <li>（1）本規約のいずれかの条項に違反した場合</li>
  <li>（2）登録事項に虚偽の事実があることが判明した場合</li>
  <li>（3）その他，当社が本サービスの利用を適当でないと判断した場合</li>
  </ul>
  </li>
  <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
  </ul>

  <h2>第8条（免責事項）</h2>
  <ul>
  <li>当社の債務不履行責任は，当社の故意または重過失によらない場合には免責されるものとします。</li>
  <li>当社は，何らかの理由によって責任を負う場合にも，通常生じうる損害の範囲内かつ有料サービスにおいては代金額（継続的サービスの場合には1か月分相当額）の範囲内においてのみ賠償の責任を負うものとします。</li>
  <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
  </ul>

  <h2>第9条（サービス内容の変更等）</h2>
  <p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

  <h2>第10条（利用規約の変更）</h2>
  <p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</p>

  <h2>第11条（通知または連絡）</h2>
  <p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。</p>

  <h2>第12条（権利義務の譲渡の禁止）</h2>
  <p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>

  <h2>第13条（準拠法・裁判管轄）</h2>
  <ul>
  <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
  <li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
  </ul>

  <p class="tR">以上</p>

</div>